<template>
    <div class="h-screen flex w-full bg-img">
        <div class="vx-col flex items-center justify-center flex-col sm:w-1/2 md:w-3/5 lg:w-3/4 xl:w-1/2 mx-auto text-center">
            <h1 class="sm:mx-0 mx-4 mb-12 text-5xl d-theme-heading-color">Políticas de Privacidad</h1>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">El presente Política de Privacidad establece los términos en que Gobierno Regional de Cusco usa y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web y el aplicativo movil MiProyecto. Esta entidad pública está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento. Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios.</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">Nuestro sitio web y aplicación movil podrá recoger información personal por ejemplo fotos de actividades diarias de los trabajos realizados en los proyecto juntamente con la ubicación geográfica. Así mismo cuando sea necesario podrá ser requerida información específica para que los funcionarios, responsables de proyectos y supervisores puedan revisar y monitores estas actividades.</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">La aplicación MiProyecto, no recoge ningún dato personal de los usuarios, no registra direcciones IP, no accede a los datos de contactos del dispositivo, no accede a las cuentas de correos de los usuarios, no guarda datos relativos al dispositivo a excepción de usar la camara para registrar la actividad realizada de una determinada tarea registrada en el aplicativo juntamente con la ultima posición GPS al momento de guardar la foto de tarea con el objetivo de registro diario de actividad.</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">Gobierno Regional de Cusco está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web.  Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opción de recibir información por correo electrónico.  En caso de que haya marcado la opción de recibir nuestro boletín o publicidad usted puede cancelarla en cualquier momento</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">La entidad no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con un orden judicial.</p>
            <p class="sm:mx-0 mx-4 mb-4 sm:mb-8 d-theme-text-black">Gobierno Regional de Cusco, se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.</p>

            <vs-button size="large" to="/">Inicio</vs-button>
        </div>
    </div>
</template>
